export const FILTER_BY_WEEK = [
    { label: "All", value: "all" },
    { label: "Week of Jul 07 – Jul 11", value: "Week of Jul 07 – Jul 11" },
    { label: "Week of Jul 14 – Jul 18", value: "Week of Jul 14 – Jul 18" },
    { label: "Week of Jul 21 – Jul 25", value: "Week of Jul 21 – Jul 25" },
    { label: "Week of Jul 28 – Aug 01", value: "Week of Jul 28 – Aug 01" },
    { label: "Week of Aug 04 – Aug 08", value: "Week of Aug 04 – Aug 08" },
    { label: "Week of Aug 11 – Aug 15", value: "Week of Aug 11 – Aug 15" },
    { label: "Week of Aug 18 – Aug 22", value: "Week of Aug 18 – Aug 22" },
    { label: "Week of Aug 25 – Aug 29", value: "Week of Aug 25 – Aug 29" },
    { label: "Week of Sep 01 – Sep 05", value: "Week of Sep 01 – Sep 05" },
    { label: "Week of Sep 08 – Sep 12", value: "Week of Sep 08 – Sep 12" },
    { label: "Week of Sep 15 – Sep 19", value: "Week of Sep 15 – Sep 19" },
    { label: "Week of Sep 22 – Sep 26", value: "Week of Sep 22 – Sep 26" },
    { label: "Week of Sep 29 – Sep 30", value: "Week of Sep 29 – Sep 30" },
]