export const FILTER_BY_STATUS = [
    { label: "All", value: 0 },
    { label: "PENDING", value: 1 },
    { label: "UNDER REVIEW", value: 2 },
    { label: "APPROVED", value: 3 },
    { label: "REJECTED", value: 4 },
    { label: "CANCELLED", value: 5 },
    { label: "ACCOMPLISHED", value: 6 },
    { label: "DECLINE", value: 7 },
    { label: "FOR TREASURER REVIEW", value: 8 },
    { label: "PAID", value: 9 },
    { label: "FOR PRINTING", value: 10 },
    { label: "RELEASED", value: 11 },
    { label: "READY FOR PICKUP", value: 12 },
];