export const RELATIONSHIPS = [
    { label: "Household Head", value: "1" },
    { label: "Family Head", value: "2" },
    { label: "Spouse", value: "3" },
    { label: "Son", value: "4" },
    { label: "Daughter", value: "5" },
    { label: "Parent", value: "6" },
    { label: "Sibling", value: "7" },
    { label: "Grandchild", value: "8" },
    { label: "Grandparent", value: "9" },
    { label: "Nephew", value: "10" },
    { label: "Niece", value: "11" },
    { label: "Uncle", value: "12" },
    { label: "Aunt", value: "13" },
    { label: "Cousin", value: "14" },
    { label: "In-Law", value: "15" },
    { label: "Boarder", value: "16" },
    { label: "Renter", value: "17" },
    { label: "Domestic Helper", value: "18" },
    { label: "Other Relative", value: "19" },
    { label: "Non-Relative", value: "20" },
]