export const RELATIONSHIP = [
    { label: "HOUSEHOLD HEAD", value: 1 },
    { label: "FAMILY HEAD", value: 2 },
    { label: "SPOUSE", value: 3 },
    { label: "MOTHER", value: 4 },
    { label: "FATHER", value: 5 },
    { label: "GUARDIAN", value: 6 },
    { label: "CHILD", value: 7 },
    { label: "SON", value: 8 },
    { label: "DAUGHTER", value: 9 },
    { label: "SIBLING", value: 10 },
    { label: "GRANDCHILD", value: 11 },
    { label: "GRANDPARENT", value: 12 },
    { label: "NEPHEW", value: 13 },
    { label: "NIECE", value: 14 },
    { label: "UNCLE", value: 15 },
    { label: "AUNT", value: 16 },
    { label: "COUSIN", value: 17 },
    { label: "IN-LAW (E.G., BROTHER-IN-LAW, SISTER-IN-LAW, PARENT-IN-LAW)", value: 18 },
    { label: "DOMESTIC HELPER", value: 19 },
    { label: "OTHER RELATIVE", value: 20 },
    { label: "NON-RELATIVE", value: 21 },
]